[METADATA]
modified = 2021-12-07T13:00:00.000Z

[[VALIDATORS]]
public_key = "nHB4cGH8jhVLc7QUwp3zysA3JxmTA7Qi2CEQgMn6Yit6E6YqDAsg"
attestation = "BBEC70B3DED5BD24E9CCC3F3073267862156AABC1AE830935FBF27DFDDEA0F94B3A32DE1AD81D1CCDCD93EF43231223B4E1913624C94C24F03CC91173EF7CB01"
network = "main"
owner_country = "de"
server_country = "de"
unl = "https://vl.xrplf.org"

[[ACCOUNTS]]
address = "rNixerUVPwrhxGDt4UooDu6FJ7zuofvjCF"
desc = "https://xrpl.services address, a website by 'Daniel Siedentopf XRP Ledger Services'"

[[ACCOUNTS]]
address = "rELeasERs3m4inA1UinRLTpXemqyStqzwh"
desc = "'XRPL Services' Escrow Releaser"

[[ACCOUNTS]]
address = "r9N4v3cWxfh4x6yUNjxNy3DbWUgbzMBLdk"
desc = "private address, owned by @nixerFFM"

[[PRINCIPALS]]
name = "XRP Ledger Services"
email = "info@xrpl.services"
twitter = "XrplServices"
